version: '3.8'

services:

  website:
    build:
      context: .
      dockerfile: ./Dockerfile.deploy
    image: website
    container_name: website
    ports:
      - "9000:9000"
    env_file:
      - envs/.env.docker
    volumes:
      - .:/application